name: Build static website and deploy

on:
  schedule:
    - cron: "0 0 1 * *" # Beginning of every month at 00:00
  workflow_dispatch:    # allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run the build
        run: npm run build
        env: 
          GSHEETS_API_KEY: ${{ secrets.GSHEETS_API_KEY }}
          GSHEETS_SPREADSHEET_ID: ${{ secrets.GSHEETS_SPREADSHEETS_ID }}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: my-pages
          clean: true